@@include('./modules/slider/slider.js')
@@include('./modules/form/range/f-range.js')
@@include('./modules/services.js')
@@include('./modules/popup/popup.js')
@@include('./modules/popup/map-popup.js')
